### ISSUE TITLE
paper

### ISSUE THREAD

**Issue by yujialele** [SherlockHolmes221/DOQ#1]
Thank you for good work! I'm very interested in it and want to further learn the details of DOQ. Please provide the Manuscript. Thanks!

**Comment by SherlockHolmes221** [comment]
The paper will be  released on CVPR official website soon, or I can e-mail you

**Comment by SherlockHolmes221** [comment]
https://openaccess.thecvf.com/content/CVPR2022/papers/Qu_Distillation_Using_Oracle_Queries_for_Transformer-Based_Human-Object_Interaction_Detection_CVPR_2022_paper.pdf
