### ISSUE TITLE
cannot import name 'build_hoi_transformer_ts_qpos_eobj_attention_map' from 'models.transformer' 

### ISSUE THREAD

**Issue by hutuo1213** [SherlockHolmes221/DOQ#6]
Hello, 'build_hoi_transformer_ts_qpos_eobj_attention_map' seems to be a module that I didn't find in 'models.transformer'.   What should I do? Thank you so much!

`Traceback (most recent call last):
  File "generate_vcoco_official.py", line 575, in <module>
    main(args)
  File "generate_vcoco_official.py", line 481, in main
    from models.transformer import build_hoi_transformer_ts_qpos_eobj_attention_map
ImportError: cannot import name 'build_hoi_transformer_ts_qpos_eobj_attention_map' from 'models.transformer' (/home1/quan107552101247/qpic/models/transformer.py)
`

**Comment by SherlockHolmes221** [comment]
please convert build_hoi_transformer_ts_qpos_eobj_attention_map to **build_hoi_ts** following hoi_share_qpos_eobj_cos_kl.py, will fix it soon

**Comment by hutuo1213** [comment]
Thank you so much! I followed your suggestions to successfully resolve this issue.

**Comment by YINNNM** [comment]
```
(pytorch) user_ym@cs_3090:~/code/DOQ$ python generate_vcoco_official.py --param_path outputs/vcoco/ts_model/checkpoint.pth --save_path vcoco.pickle --hoi_path ~/code/dataset/vcoco --model_name hoi_ts_qpos_eobj_kl
git:
  sha: de1bc1397e6e94a5449cb16101b1f93ae7220eb5, status: has uncommited changes, branch: main

Namespace(backbone='resnet50', batch_size=2, dataset_file='vcoco', dec_layers=6, device='cuda', dilation=False, dim_feedforward=2048, dropout=0.1, enc_layers=6, hidden_dim=256, hoi_path='/home/user_ym/code/dataset/vcoco', missing_category_id=80, model_name='hoi_ts_qpos_eobj_kl', nheads=8, num_obj_classes=80, num_queries=100, num_verb_classes=117, num_verb_queries=100, num_workers=2, param_path='outputs/vcoco/ts_model/checkpoint.pth', position_embedding='sine', pre_norm=False, save_path='vcoco.pickle', subject_category_id=0)
Traceback (most recent call last):
  File "generate_vcoco_official.py", line 579, in <module>
    main(args)
  File "generate_vcoco_official.py", line 488, in main
    num_verb_classes=args.num_verb_classes)
TypeError: build_hoi_ts() got an unexpected keyword argument 'begin_l'
```


May I ask if you have had this problem? How do I fix it?
